import OpenAI from "openai";

// AI generation with graceful fallback.
// If OpenAI is unavailable (no key, rate limit, error), returns
// a simulated draft. The scheduling patterns work identically either way.

const openai = process.env.OPENAI_API_KEY
  ? new OpenAI({ apiKey: process.env.OPENAI_API_KEY })
  : null;

export async function generateDraft(
  prompt: string,
  contentType: string
): Promise<string> {
  if (!openai) {
    return mockGenerate(prompt, contentType);
  }

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are a content writer. Generate a ${contentType} based on the user's prompt. Keep it concise and professional.`,
        },
        { role: "user", content: prompt },
      ],
      max_tokens: 250,
    });

    return (
      completion.choices[0]?.message?.content ??
      mockGenerate(prompt, contentType)
    );
  } catch (err) {
    console.error("[ai] OpenAI error, falling back to simulated draft:", (err as Error).message);
    return mockGenerate(prompt, contentType);
  }
}

function mockGenerate(prompt: string, contentType: string): string {
  return [
    `# Draft ${contentType}`,
    "",
    `Based on your prompt: "${prompt}"`,
    "",
    "This is a simulated draft. In the starter, this would be generated by OpenAI.",
    "",
    "The scheduling patterns (reminders, expirations, snooze) work identically with real or simulated content.",
  ].join("\n");
}
